// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: rollup/v1/consensus.proto

package rollupv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// XtID represents a transaction ID (SHA256 hash)
type XtID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          []byte                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"` // 32-byte SHA256 hash
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *XtID) Reset() {
	*x = XtID{}
	mi := &file_rollup_v1_consensus_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *XtID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XtID) ProtoMessage() {}

func (x *XtID) ProtoReflect() protoreflect.Message {
	mi := &file_rollup_v1_consensus_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XtID.ProtoReflect.Descriptor instead.
func (*XtID) Descriptor() ([]byte, []int) {
	return file_rollup_v1_consensus_proto_rawDescGZIP(), []int{0}
}

func (x *XtID) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

// XTRequest represents a cross-chain transaction request
type XTRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*TransactionRequest  `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *XTRequest) Reset() {
	*x = XTRequest{}
	mi := &file_rollup_v1_consensus_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *XTRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XTRequest) ProtoMessage() {}

func (x *XTRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rollup_v1_consensus_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XTRequest.ProtoReflect.Descriptor instead.
func (*XTRequest) Descriptor() ([]byte, []int) {
	return file_rollup_v1_consensus_proto_rawDescGZIP(), []int{1}
}

func (x *XTRequest) GetTransactions() []*TransactionRequest {
	if x != nil {
		return x.Transactions
	}
	return nil
}

// TransactionRequest represents a single transaction request for a specific chain
type TransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainId       []byte                 `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Transaction   [][]byte               `protobuf:"bytes,2,rep,name=transaction,proto3" json:"transaction,omitempty"` // RLP encoded Ethereum transactions
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionRequest) Reset() {
	*x = TransactionRequest{}
	mi := &file_rollup_v1_consensus_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionRequest) ProtoMessage() {}

func (x *TransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rollup_v1_consensus_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionRequest.ProtoReflect.Descriptor instead.
func (*TransactionRequest) Descriptor() ([]byte, []int) {
	return file_rollup_v1_consensus_proto_rawDescGZIP(), []int{2}
}

func (x *TransactionRequest) GetChainId() []byte {
	if x != nil {
		return x.ChainId
	}
	return nil
}

func (x *TransactionRequest) GetTransaction() [][]byte {
	if x != nil {
		return x.Transaction
	}
	return nil
}

// Vote is a 2PC vote message from a sequencer to the SP
type Vote struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SenderChainId []byte                 `protobuf:"bytes,1,opt,name=sender_chain_id,json=senderChainId,proto3" json:"sender_chain_id,omitempty"` // Which chain is voting
	XtId          *XtID                  `protobuf:"bytes,2,opt,name=xt_id,json=xtId,proto3" json:"xt_id,omitempty"`                              // Transaction ID
	Vote          bool                   `protobuf:"varint,3,opt,name=vote,proto3" json:"vote,omitempty"`                                         // true = Commit, false = Abort
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vote) Reset() {
	*x = Vote{}
	mi := &file_rollup_v1_consensus_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vote) ProtoMessage() {}

func (x *Vote) ProtoReflect() protoreflect.Message {
	mi := &file_rollup_v1_consensus_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vote.ProtoReflect.Descriptor instead.
func (*Vote) Descriptor() ([]byte, []int) {
	return file_rollup_v1_consensus_proto_rawDescGZIP(), []int{3}
}

func (x *Vote) GetSenderChainId() []byte {
	if x != nil {
		return x.SenderChainId
	}
	return nil
}

func (x *Vote) GetXtId() *XtID {
	if x != nil {
		return x.XtId
	}
	return nil
}

func (x *Vote) GetVote() bool {
	if x != nil {
		return x.Vote
	}
	return false
}

// Decided is a 2PC decision message from the SP to sequencers
type Decided struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	XtId          *XtID                  `protobuf:"bytes,1,opt,name=xt_id,json=xtId,proto3" json:"xt_id,omitempty"` // Transaction ID
	Decision      bool                   `protobuf:"varint,2,opt,name=decision,proto3" json:"decision,omitempty"`    // true = Commit, false = Abort
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Decided) Reset() {
	*x = Decided{}
	mi := &file_rollup_v1_consensus_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Decided) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Decided) ProtoMessage() {}

func (x *Decided) ProtoReflect() protoreflect.Message {
	mi := &file_rollup_v1_consensus_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Decided.ProtoReflect.Descriptor instead.
func (*Decided) Descriptor() ([]byte, []int) {
	return file_rollup_v1_consensus_proto_rawDescGZIP(), []int{4}
}

func (x *Decided) GetXtId() *XtID {
	if x != nil {
		return x.XtId
	}
	return nil
}

func (x *Decided) GetDecision() bool {
	if x != nil {
		return x.Decision
	}
	return false
}

// CIRCMessage for direct message exchange between sequencers
type CIRCMessage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SourceChain      []byte                 `protobuf:"bytes,1,opt,name=source_chain,json=sourceChain,proto3" json:"source_chain,omitempty"`
	DestinationChain []byte                 `protobuf:"bytes,2,opt,name=destination_chain,json=destinationChain,proto3" json:"destination_chain,omitempty"`
	Source           [][]byte               `protobuf:"bytes,3,rep,name=source,proto3" json:"source,omitempty"`
	Receiver         [][]byte               `protobuf:"bytes,4,rep,name=receiver,proto3" json:"receiver,omitempty"`
	XtId             *XtID                  `protobuf:"bytes,5,opt,name=xt_id,json=xtId,proto3" json:"xt_id,omitempty"`
	Label            string                 `protobuf:"bytes,6,opt,name=label,proto3" json:"label,omitempty"`
	Data             [][]byte               `protobuf:"bytes,7,rep,name=data,proto3" json:"data,omitempty"`                            // ABI encoded data
	SessionId        []byte                 `protobuf:"bytes,8,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // 32-byte big-endian session identifier (U256)
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CIRCMessage) Reset() {
	*x = CIRCMessage{}
	mi := &file_rollup_v1_consensus_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CIRCMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CIRCMessage) ProtoMessage() {}

func (x *CIRCMessage) ProtoReflect() protoreflect.Message {
	mi := &file_rollup_v1_consensus_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CIRCMessage.ProtoReflect.Descriptor instead.
func (*CIRCMessage) Descriptor() ([]byte, []int) {
	return file_rollup_v1_consensus_proto_rawDescGZIP(), []int{5}
}

func (x *CIRCMessage) GetSourceChain() []byte {
	if x != nil {
		return x.SourceChain
	}
	return nil
}

func (x *CIRCMessage) GetDestinationChain() []byte {
	if x != nil {
		return x.DestinationChain
	}
	return nil
}

func (x *CIRCMessage) GetSource() [][]byte {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *CIRCMessage) GetReceiver() [][]byte {
	if x != nil {
		return x.Receiver
	}
	return nil
}

func (x *CIRCMessage) GetXtId() *XtID {
	if x != nil {
		return x.XtId
	}
	return nil
}

func (x *CIRCMessage) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *CIRCMessage) GetData() [][]byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CIRCMessage) GetSessionId() []byte {
	if x != nil {
		return x.SessionId
	}
	return nil
}

var File_rollup_v1_consensus_proto protoreflect.FileDescriptor

const file_rollup_v1_consensus_proto_rawDesc = "" +
	"\n" +
	"\x19rollup/v1/consensus.proto\x12\trollup.v1\"\x1a\n" +
	"\x04XtID\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\fR\x04hash\"N\n" +
	"\tXTRequest\x12A\n" +
	"\ftransactions\x18\x01 \x03(\v2\x1d.rollup.v1.TransactionRequestR\ftransactions\"Q\n" +
	"\x12TransactionRequest\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\fR\achainId\x12 \n" +
	"\vtransaction\x18\x02 \x03(\fR\vtransaction\"h\n" +
	"\x04Vote\x12&\n" +
	"\x0fsender_chain_id\x18\x01 \x01(\fR\rsenderChainId\x12$\n" +
	"\x05xt_id\x18\x02 \x01(\v2\x0f.rollup.v1.XtIDR\x04xtId\x12\x12\n" +
	"\x04vote\x18\x03 \x01(\bR\x04vote\"K\n" +
	"\aDecided\x12$\n" +
	"\x05xt_id\x18\x01 \x01(\v2\x0f.rollup.v1.XtIDR\x04xtId\x12\x1a\n" +
	"\bdecision\x18\x02 \x01(\bR\bdecision\"\x80\x02\n" +
	"\vCIRCMessage\x12!\n" +
	"\fsource_chain\x18\x01 \x01(\fR\vsourceChain\x12+\n" +
	"\x11destination_chain\x18\x02 \x01(\fR\x10destinationChain\x12\x16\n" +
	"\x06source\x18\x03 \x03(\fR\x06source\x12\x1a\n" +
	"\breceiver\x18\x04 \x03(\fR\breceiver\x12$\n" +
	"\x05xt_id\x18\x05 \x01(\v2\x0f.rollup.v1.XtIDR\x04xtId\x12\x14\n" +
	"\x05label\x18\x06 \x01(\tR\x05label\x12\x12\n" +
	"\x04data\x18\a \x03(\fR\x04data\x12\x1d\n" +
	"\n" +
	"session_id\x18\b \x01(\fR\tsessionIdB\xa3\x01\n" +
	"\rcom.rollup.v1B\x0eConsensusProtoP\x01Z=github.com/compose-network/publisher/proto/rollup/v1;rollupv1\xa2\x02\x03RXX\xaa\x02\tRollup.V1\xca\x02\tRollup\\V1\xe2\x02\x15Rollup\\V1\\GPBMetadata\xea\x02\n" +
	"Rollup::V1b\x06proto3"

var (
	file_rollup_v1_consensus_proto_rawDescOnce sync.Once
	file_rollup_v1_consensus_proto_rawDescData []byte
)

func file_rollup_v1_consensus_proto_rawDescGZIP() []byte {
	file_rollup_v1_consensus_proto_rawDescOnce.Do(func() {
		file_rollup_v1_consensus_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rollup_v1_consensus_proto_rawDesc), len(file_rollup_v1_consensus_proto_rawDesc)))
	})
	return file_rollup_v1_consensus_proto_rawDescData
}

var file_rollup_v1_consensus_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_rollup_v1_consensus_proto_goTypes = []any{
	(*XtID)(nil),               // 0: rollup.v1.XtID
	(*XTRequest)(nil),          // 1: rollup.v1.XTRequest
	(*TransactionRequest)(nil), // 2: rollup.v1.TransactionRequest
	(*Vote)(nil),               // 3: rollup.v1.Vote
	(*Decided)(nil),            // 4: rollup.v1.Decided
	(*CIRCMessage)(nil),        // 5: rollup.v1.CIRCMessage
}
var file_rollup_v1_consensus_proto_depIdxs = []int32{
	2, // 0: rollup.v1.XTRequest.transactions:type_name -> rollup.v1.TransactionRequest
	0, // 1: rollup.v1.Vote.xt_id:type_name -> rollup.v1.XtID
	0, // 2: rollup.v1.Decided.xt_id:type_name -> rollup.v1.XtID
	0, // 3: rollup.v1.CIRCMessage.xt_id:type_name -> rollup.v1.XtID
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_rollup_v1_consensus_proto_init() }
func file_rollup_v1_consensus_proto_init() {
	if File_rollup_v1_consensus_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rollup_v1_consensus_proto_rawDesc), len(file_rollup_v1_consensus_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rollup_v1_consensus_proto_goTypes,
		DependencyIndexes: file_rollup_v1_consensus_proto_depIdxs,
		MessageInfos:      file_rollup_v1_consensus_proto_msgTypes,
	}.Build()
	File_rollup_v1_consensus_proto = out.File
	file_rollup_v1_consensus_proto_goTypes = nil
	file_rollup_v1_consensus_proto_depIdxs = nil
}
