// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: rollup/v1/messages.proto

package rollupv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Message is the main wrapper for all protocol messages
// This allows multiplexing different message types over a single connection
type Message struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	SenderId string                 `protobuf:"bytes,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"` // Identifier of the sender
	// Payload contains the actual message content
	//
	// Types that are valid to be assigned to Payload:
	//
	//	*Message_XtRequest
	//	*Message_Vote
	//	*Message_Decided
	//	*Message_Block
	//	*Message_CircMessage
	//	*Message_StartSlot
	//	*Message_RequestSeal
	//	*Message_RollBackAndStartSlot
	//	*Message_L2Block
	//	*Message_StartSc
	//	*Message_HandshakeRequest
	//	*Message_HandshakeResponse
	//	*Message_Ping
	//	*Message_Pong
	//	*Message_Disconnect
	Payload       isMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_rollup_v1_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_rollup_v1_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_rollup_v1_messages_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *Message) GetPayload() isMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Message) GetXtRequest() *XTRequest {
	if x != nil {
		if x, ok := x.Payload.(*Message_XtRequest); ok {
			return x.XtRequest
		}
	}
	return nil
}

func (x *Message) GetVote() *Vote {
	if x != nil {
		if x, ok := x.Payload.(*Message_Vote); ok {
			return x.Vote
		}
	}
	return nil
}

func (x *Message) GetDecided() *Decided {
	if x != nil {
		if x, ok := x.Payload.(*Message_Decided); ok {
			return x.Decided
		}
	}
	return nil
}

func (x *Message) GetBlock() *Block {
	if x != nil {
		if x, ok := x.Payload.(*Message_Block); ok {
			return x.Block
		}
	}
	return nil
}

func (x *Message) GetCircMessage() *CIRCMessage {
	if x != nil {
		if x, ok := x.Payload.(*Message_CircMessage); ok {
			return x.CircMessage
		}
	}
	return nil
}

func (x *Message) GetStartSlot() *StartSlot {
	if x != nil {
		if x, ok := x.Payload.(*Message_StartSlot); ok {
			return x.StartSlot
		}
	}
	return nil
}

func (x *Message) GetRequestSeal() *RequestSeal {
	if x != nil {
		if x, ok := x.Payload.(*Message_RequestSeal); ok {
			return x.RequestSeal
		}
	}
	return nil
}

func (x *Message) GetRollBackAndStartSlot() *RollBackAndStartSlot {
	if x != nil {
		if x, ok := x.Payload.(*Message_RollBackAndStartSlot); ok {
			return x.RollBackAndStartSlot
		}
	}
	return nil
}

func (x *Message) GetL2Block() *L2Block {
	if x != nil {
		if x, ok := x.Payload.(*Message_L2Block); ok {
			return x.L2Block
		}
	}
	return nil
}

func (x *Message) GetStartSc() *StartSC {
	if x != nil {
		if x, ok := x.Payload.(*Message_StartSc); ok {
			return x.StartSc
		}
	}
	return nil
}

func (x *Message) GetHandshakeRequest() *HandshakeRequest {
	if x != nil {
		if x, ok := x.Payload.(*Message_HandshakeRequest); ok {
			return x.HandshakeRequest
		}
	}
	return nil
}

func (x *Message) GetHandshakeResponse() *HandshakeResponse {
	if x != nil {
		if x, ok := x.Payload.(*Message_HandshakeResponse); ok {
			return x.HandshakeResponse
		}
	}
	return nil
}

func (x *Message) GetPing() *Ping {
	if x != nil {
		if x, ok := x.Payload.(*Message_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *Message) GetPong() *Pong {
	if x != nil {
		if x, ok := x.Payload.(*Message_Pong); ok {
			return x.Pong
		}
	}
	return nil
}

func (x *Message) GetDisconnect() *DisconnectMessage {
	if x != nil {
		if x, ok := x.Payload.(*Message_Disconnect); ok {
			return x.Disconnect
		}
	}
	return nil
}

type isMessage_Payload interface {
	isMessage_Payload()
}

type Message_XtRequest struct {
	// SCP (Synchronous Composability Protocol) messages
	XtRequest *XTRequest `protobuf:"bytes,2,opt,name=xt_request,json=xtRequest,proto3,oneof"`
}

type Message_Vote struct {
	Vote *Vote `protobuf:"bytes,3,opt,name=vote,proto3,oneof"`
}

type Message_Decided struct {
	Decided *Decided `protobuf:"bytes,4,opt,name=decided,proto3,oneof"`
}

type Message_Block struct {
	Block *Block `protobuf:"bytes,5,opt,name=block,proto3,oneof"` // Deprecated
}

type Message_CircMessage struct {
	CircMessage *CIRCMessage `protobuf:"bytes,6,opt,name=circ_message,json=circMessage,proto3,oneof"`
}

type Message_StartSlot struct {
	// SBCP (Superblock Construction Protocol) messages
	StartSlot *StartSlot `protobuf:"bytes,7,opt,name=start_slot,json=startSlot,proto3,oneof"`
}

type Message_RequestSeal struct {
	RequestSeal *RequestSeal `protobuf:"bytes,8,opt,name=request_seal,json=requestSeal,proto3,oneof"`
}

type Message_RollBackAndStartSlot struct {
	RollBackAndStartSlot *RollBackAndStartSlot `protobuf:"bytes,9,opt,name=roll_back_and_start_slot,json=rollBackAndStartSlot,proto3,oneof"`
}

type Message_L2Block struct {
	L2Block *L2Block `protobuf:"bytes,10,opt,name=l2_block,json=l2Block,proto3,oneof"`
}

type Message_StartSc struct {
	StartSc *StartSC `protobuf:"bytes,11,opt,name=start_sc,json=startSc,proto3,oneof"`
}

type Message_HandshakeRequest struct {
	// Transport-level messages
	HandshakeRequest *HandshakeRequest `protobuf:"bytes,12,opt,name=handshake_request,json=handshakeRequest,proto3,oneof"`
}

type Message_HandshakeResponse struct {
	HandshakeResponse *HandshakeResponse `protobuf:"bytes,13,opt,name=handshake_response,json=handshakeResponse,proto3,oneof"`
}

type Message_Ping struct {
	Ping *Ping `protobuf:"bytes,14,opt,name=ping,proto3,oneof"`
}

type Message_Pong struct {
	Pong *Pong `protobuf:"bytes,15,opt,name=pong,proto3,oneof"`
}

type Message_Disconnect struct {
	Disconnect *DisconnectMessage `protobuf:"bytes,16,opt,name=disconnect,proto3,oneof"`
}

func (*Message_XtRequest) isMessage_Payload() {}

func (*Message_Vote) isMessage_Payload() {}

func (*Message_Decided) isMessage_Payload() {}

func (*Message_Block) isMessage_Payload() {}

func (*Message_CircMessage) isMessage_Payload() {}

func (*Message_StartSlot) isMessage_Payload() {}

func (*Message_RequestSeal) isMessage_Payload() {}

func (*Message_RollBackAndStartSlot) isMessage_Payload() {}

func (*Message_L2Block) isMessage_Payload() {}

func (*Message_StartSc) isMessage_Payload() {}

func (*Message_HandshakeRequest) isMessage_Payload() {}

func (*Message_HandshakeResponse) isMessage_Payload() {}

func (*Message_Ping) isMessage_Payload() {}

func (*Message_Pong) isMessage_Payload() {}

func (*Message_Disconnect) isMessage_Payload() {}

var File_rollup_v1_messages_proto protoreflect.FileDescriptor

const file_rollup_v1_messages_proto_rawDesc = "" +
	"\n" +
	"\x18rollup/v1/messages.proto\x12\trollup.v1\x1a\x19rollup/v1/transport.proto\x1a\x19rollup/v1/consensus.proto\x1a\x14rollup/v1/sbcp.proto\"\x80\a\n" +
	"\aMessage\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\tR\bsenderId\x125\n" +
	"\n" +
	"xt_request\x18\x02 \x01(\v2\x14.rollup.v1.XTRequestH\x00R\txtRequest\x12%\n" +
	"\x04vote\x18\x03 \x01(\v2\x0f.rollup.v1.VoteH\x00R\x04vote\x12.\n" +
	"\adecided\x18\x04 \x01(\v2\x12.rollup.v1.DecidedH\x00R\adecided\x12(\n" +
	"\x05block\x18\x05 \x01(\v2\x10.rollup.v1.BlockH\x00R\x05block\x12;\n" +
	"\fcirc_message\x18\x06 \x01(\v2\x16.rollup.v1.CIRCMessageH\x00R\vcircMessage\x125\n" +
	"\n" +
	"start_slot\x18\a \x01(\v2\x14.rollup.v1.StartSlotH\x00R\tstartSlot\x12;\n" +
	"\frequest_seal\x18\b \x01(\v2\x16.rollup.v1.RequestSealH\x00R\vrequestSeal\x12Y\n" +
	"\x18roll_back_and_start_slot\x18\t \x01(\v2\x1f.rollup.v1.RollBackAndStartSlotH\x00R\x14rollBackAndStartSlot\x12/\n" +
	"\bl2_block\x18\n" +
	" \x01(\v2\x12.rollup.v1.L2BlockH\x00R\al2Block\x12/\n" +
	"\bstart_sc\x18\v \x01(\v2\x12.rollup.v1.StartSCH\x00R\astartSc\x12J\n" +
	"\x11handshake_request\x18\f \x01(\v2\x1b.rollup.v1.HandshakeRequestH\x00R\x10handshakeRequest\x12M\n" +
	"\x12handshake_response\x18\r \x01(\v2\x1c.rollup.v1.HandshakeResponseH\x00R\x11handshakeResponse\x12%\n" +
	"\x04ping\x18\x0e \x01(\v2\x0f.rollup.v1.PingH\x00R\x04ping\x12%\n" +
	"\x04pong\x18\x0f \x01(\v2\x0f.rollup.v1.PongH\x00R\x04pong\x12>\n" +
	"\n" +
	"disconnect\x18\x10 \x01(\v2\x1c.rollup.v1.DisconnectMessageH\x00R\n" +
	"disconnectB\t\n" +
	"\apayloadB\xa2\x01\n" +
	"\rcom.rollup.v1B\rMessagesProtoP\x01Z=github.com/compose-network/publisher/proto/rollup/v1;rollupv1\xa2\x02\x03RXX\xaa\x02\tRollup.V1\xca\x02\tRollup\\V1\xe2\x02\x15Rollup\\V1\\GPBMetadata\xea\x02\n" +
	"Rollup::V1b\x06proto3"

var (
	file_rollup_v1_messages_proto_rawDescOnce sync.Once
	file_rollup_v1_messages_proto_rawDescData []byte
)

func file_rollup_v1_messages_proto_rawDescGZIP() []byte {
	file_rollup_v1_messages_proto_rawDescOnce.Do(func() {
		file_rollup_v1_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rollup_v1_messages_proto_rawDesc), len(file_rollup_v1_messages_proto_rawDesc)))
	})
	return file_rollup_v1_messages_proto_rawDescData
}

var file_rollup_v1_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_rollup_v1_messages_proto_goTypes = []any{
	(*Message)(nil),              // 0: rollup.v1.Message
	(*XTRequest)(nil),            // 1: rollup.v1.XTRequest
	(*Vote)(nil),                 // 2: rollup.v1.Vote
	(*Decided)(nil),              // 3: rollup.v1.Decided
	(*Block)(nil),                // 4: rollup.v1.Block
	(*CIRCMessage)(nil),          // 5: rollup.v1.CIRCMessage
	(*StartSlot)(nil),            // 6: rollup.v1.StartSlot
	(*RequestSeal)(nil),          // 7: rollup.v1.RequestSeal
	(*RollBackAndStartSlot)(nil), // 8: rollup.v1.RollBackAndStartSlot
	(*L2Block)(nil),              // 9: rollup.v1.L2Block
	(*StartSC)(nil),              // 10: rollup.v1.StartSC
	(*HandshakeRequest)(nil),     // 11: rollup.v1.HandshakeRequest
	(*HandshakeResponse)(nil),    // 12: rollup.v1.HandshakeResponse
	(*Ping)(nil),                 // 13: rollup.v1.Ping
	(*Pong)(nil),                 // 14: rollup.v1.Pong
	(*DisconnectMessage)(nil),    // 15: rollup.v1.DisconnectMessage
}
var file_rollup_v1_messages_proto_depIdxs = []int32{
	1,  // 0: rollup.v1.Message.xt_request:type_name -> rollup.v1.XTRequest
	2,  // 1: rollup.v1.Message.vote:type_name -> rollup.v1.Vote
	3,  // 2: rollup.v1.Message.decided:type_name -> rollup.v1.Decided
	4,  // 3: rollup.v1.Message.block:type_name -> rollup.v1.Block
	5,  // 4: rollup.v1.Message.circ_message:type_name -> rollup.v1.CIRCMessage
	6,  // 5: rollup.v1.Message.start_slot:type_name -> rollup.v1.StartSlot
	7,  // 6: rollup.v1.Message.request_seal:type_name -> rollup.v1.RequestSeal
	8,  // 7: rollup.v1.Message.roll_back_and_start_slot:type_name -> rollup.v1.RollBackAndStartSlot
	9,  // 8: rollup.v1.Message.l2_block:type_name -> rollup.v1.L2Block
	10, // 9: rollup.v1.Message.start_sc:type_name -> rollup.v1.StartSC
	11, // 10: rollup.v1.Message.handshake_request:type_name -> rollup.v1.HandshakeRequest
	12, // 11: rollup.v1.Message.handshake_response:type_name -> rollup.v1.HandshakeResponse
	13, // 12: rollup.v1.Message.ping:type_name -> rollup.v1.Ping
	14, // 13: rollup.v1.Message.pong:type_name -> rollup.v1.Pong
	15, // 14: rollup.v1.Message.disconnect:type_name -> rollup.v1.DisconnectMessage
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_rollup_v1_messages_proto_init() }
func file_rollup_v1_messages_proto_init() {
	if File_rollup_v1_messages_proto != nil {
		return
	}
	file_rollup_v1_transport_proto_init()
	file_rollup_v1_consensus_proto_init()
	file_rollup_v1_sbcp_proto_init()
	file_rollup_v1_messages_proto_msgTypes[0].OneofWrappers = []any{
		(*Message_XtRequest)(nil),
		(*Message_Vote)(nil),
		(*Message_Decided)(nil),
		(*Message_Block)(nil),
		(*Message_CircMessage)(nil),
		(*Message_StartSlot)(nil),
		(*Message_RequestSeal)(nil),
		(*Message_RollBackAndStartSlot)(nil),
		(*Message_L2Block)(nil),
		(*Message_StartSc)(nil),
		(*Message_HandshakeRequest)(nil),
		(*Message_HandshakeResponse)(nil),
		(*Message_Ping)(nil),
		(*Message_Pong)(nil),
		(*Message_Disconnect)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rollup_v1_messages_proto_rawDesc), len(file_rollup_v1_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rollup_v1_messages_proto_goTypes,
		DependencyIndexes: file_rollup_v1_messages_proto_depIdxs,
		MessageInfos:      file_rollup_v1_messages_proto_msgTypes,
	}.Build()
	File_rollup_v1_messages_proto = out.File
	file_rollup_v1_messages_proto_goTypes = nil
	file_rollup_v1_messages_proto_depIdxs = nil
}
