// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: rollup/v1/sbcp.proto

package rollupv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// L2BlockRequest specifies which L2 block a sequencer should build
type L2BlockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainId       []byte                 `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	BlockNumber   uint64                 `protobuf:"varint,2,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	ParentHash    []byte                 `protobuf:"bytes,3,opt,name=parent_hash,json=parentHash,proto3" json:"parent_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *L2BlockRequest) Reset() {
	*x = L2BlockRequest{}
	mi := &file_rollup_v1_sbcp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *L2BlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L2BlockRequest) ProtoMessage() {}

func (x *L2BlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rollup_v1_sbcp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L2BlockRequest.ProtoReflect.Descriptor instead.
func (*L2BlockRequest) Descriptor() ([]byte, []int) {
	return file_rollup_v1_sbcp_proto_rawDescGZIP(), []int{0}
}

func (x *L2BlockRequest) GetChainId() []byte {
	if x != nil {
		return x.ChainId
	}
	return nil
}

func (x *L2BlockRequest) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *L2BlockRequest) GetParentHash() []byte {
	if x != nil {
		return x.ParentHash
	}
	return nil
}

// StartSlot is sent by SP to begin a new slot
type StartSlot struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Slot                 uint64                 `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`                                                               // Current slot number
	NextSuperblockNumber uint64                 `protobuf:"varint,2,opt,name=next_superblock_number,json=nextSuperblockNumber,proto3" json:"next_superblock_number,omitempty"` // Superblock number SP aims to produce
	LastSuperblockHash   []byte                 `protobuf:"bytes,3,opt,name=last_superblock_hash,json=lastSuperblockHash,proto3" json:"last_superblock_hash,omitempty"`        // Hash of the last valid superblock
	L2BlocksRequest      []*L2BlockRequest      `protobuf:"bytes,4,rep,name=l2_blocks_request,json=l2BlocksRequest,proto3" json:"l2_blocks_request,omitempty"`                 // L2 blocks to be built by each rollup
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *StartSlot) Reset() {
	*x = StartSlot{}
	mi := &file_rollup_v1_sbcp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSlot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSlot) ProtoMessage() {}

func (x *StartSlot) ProtoReflect() protoreflect.Message {
	mi := &file_rollup_v1_sbcp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSlot.ProtoReflect.Descriptor instead.
func (*StartSlot) Descriptor() ([]byte, []int) {
	return file_rollup_v1_sbcp_proto_rawDescGZIP(), []int{1}
}

func (x *StartSlot) GetSlot() uint64 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *StartSlot) GetNextSuperblockNumber() uint64 {
	if x != nil {
		return x.NextSuperblockNumber
	}
	return 0
}

func (x *StartSlot) GetLastSuperblockHash() []byte {
	if x != nil {
		return x.LastSuperblockHash
	}
	return nil
}

func (x *StartSlot) GetL2BlocksRequest() []*L2BlockRequest {
	if x != nil {
		return x.L2BlocksRequest
	}
	return nil
}

// RequestSeal is sent by SP to request sequencers seal their blocks
type RequestSeal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          uint64                 `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`                                 // Current slot number
	IncludedXts   [][]byte               `protobuf:"bytes,2,rep,name=included_xts,json=includedXts,proto3" json:"included_xts,omitempty"` // List of included cross-chain transaction IDs
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestSeal) Reset() {
	*x = RequestSeal{}
	mi := &file_rollup_v1_sbcp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestSeal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestSeal) ProtoMessage() {}

func (x *RequestSeal) ProtoReflect() protoreflect.Message {
	mi := &file_rollup_v1_sbcp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestSeal.ProtoReflect.Descriptor instead.
func (*RequestSeal) Descriptor() ([]byte, []int) {
	return file_rollup_v1_sbcp_proto_rawDescGZIP(), []int{2}
}

func (x *RequestSeal) GetSlot() uint64 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *RequestSeal) GetIncludedXts() [][]byte {
	if x != nil {
		return x.IncludedXts
	}
	return nil
}

// RollBackAndStartSlot is sent by SP to rollback and restart from a valid state
type RollBackAndStartSlot struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	L2BlocksRequest      []*L2BlockRequest      `protobuf:"bytes,1,rep,name=l2_blocks_request,json=l2BlocksRequest,proto3" json:"l2_blocks_request,omitempty"`                 // L2 blocks to build from valid state
	CurrentSlot          uint64                 `protobuf:"varint,2,opt,name=current_slot,json=currentSlot,proto3" json:"current_slot,omitempty"`                              // Current slot number
	NextSuperblockNumber uint64                 `protobuf:"varint,3,opt,name=next_superblock_number,json=nextSuperblockNumber,proto3" json:"next_superblock_number,omitempty"` // Next superblock number to produce
	LastSuperblockHash   []byte                 `protobuf:"bytes,4,opt,name=last_superblock_hash,json=lastSuperblockHash,proto3" json:"last_superblock_hash,omitempty"`        // Hash of last valid superblock
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *RollBackAndStartSlot) Reset() {
	*x = RollBackAndStartSlot{}
	mi := &file_rollup_v1_sbcp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollBackAndStartSlot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollBackAndStartSlot) ProtoMessage() {}

func (x *RollBackAndStartSlot) ProtoReflect() protoreflect.Message {
	mi := &file_rollup_v1_sbcp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollBackAndStartSlot.ProtoReflect.Descriptor instead.
func (*RollBackAndStartSlot) Descriptor() ([]byte, []int) {
	return file_rollup_v1_sbcp_proto_rawDescGZIP(), []int{3}
}

func (x *RollBackAndStartSlot) GetL2BlocksRequest() []*L2BlockRequest {
	if x != nil {
		return x.L2BlocksRequest
	}
	return nil
}

func (x *RollBackAndStartSlot) GetCurrentSlot() uint64 {
	if x != nil {
		return x.CurrentSlot
	}
	return 0
}

func (x *RollBackAndStartSlot) GetNextSuperblockNumber() uint64 {
	if x != nil {
		return x.NextSuperblockNumber
	}
	return 0
}

func (x *RollBackAndStartSlot) GetLastSuperblockHash() []byte {
	if x != nil {
		return x.LastSuperblockHash
	}
	return nil
}

// L2Block is submitted from sequencer to SP
type L2Block struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Slot            uint64                 `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`                                               // Slot this block belongs to
	ChainId         []byte                 `protobuf:"bytes,2,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`                           // Chain identifier
	BlockNumber     uint64                 `protobuf:"varint,3,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`              // L2 block number
	BlockHash       []byte                 `protobuf:"bytes,4,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`                     // Hash of this L2 block
	ParentBlockHash []byte                 `protobuf:"bytes,5,opt,name=parent_block_hash,json=parentBlockHash,proto3" json:"parent_block_hash,omitempty"` // Hash of parent L2 block
	IncludedXts     [][]byte               `protobuf:"bytes,6,rep,name=included_xts,json=includedXts,proto3" json:"included_xts,omitempty"`               // Included cross-chain transaction IDs
	Block           []byte                 `protobuf:"bytes,7,opt,name=block,proto3" json:"block,omitempty"`                                              // Encoded Ethereum block data (RLP encoded)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *L2Block) Reset() {
	*x = L2Block{}
	mi := &file_rollup_v1_sbcp_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *L2Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L2Block) ProtoMessage() {}

func (x *L2Block) ProtoReflect() protoreflect.Message {
	mi := &file_rollup_v1_sbcp_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L2Block.ProtoReflect.Descriptor instead.
func (*L2Block) Descriptor() ([]byte, []int) {
	return file_rollup_v1_sbcp_proto_rawDescGZIP(), []int{4}
}

func (x *L2Block) GetSlot() uint64 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *L2Block) GetChainId() []byte {
	if x != nil {
		return x.ChainId
	}
	return nil
}

func (x *L2Block) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *L2Block) GetBlockHash() []byte {
	if x != nil {
		return x.BlockHash
	}
	return nil
}

func (x *L2Block) GetParentBlockHash() []byte {
	if x != nil {
		return x.ParentBlockHash
	}
	return nil
}

func (x *L2Block) GetIncludedXts() [][]byte {
	if x != nil {
		return x.IncludedXts
	}
	return nil
}

func (x *L2Block) GetBlock() []byte {
	if x != nil {
		return x.Block
	}
	return nil
}

// StartSC is sent by SP to start cross-chain transaction coordination
type StartSC struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Slot             uint64                 `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`                                                   // Current slot number
	XtSequenceNumber uint64                 `protobuf:"varint,2,opt,name=xt_sequence_number,json=xtSequenceNumber,proto3" json:"xt_sequence_number,omitempty"` // Sequence number for ordering within slot
	XtRequest        *XTRequest             `protobuf:"bytes,3,opt,name=xt_request,json=xtRequest,proto3" json:"xt_request,omitempty"`                         // The cross-chain transaction request
	XtId             []byte                 `protobuf:"bytes,4,opt,name=xt_id,json=xtId,proto3" json:"xt_id,omitempty"`                                        // 32-byte SHA256 hash over xTRequest
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StartSC) Reset() {
	*x = StartSC{}
	mi := &file_rollup_v1_sbcp_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSC) ProtoMessage() {}

func (x *StartSC) ProtoReflect() protoreflect.Message {
	mi := &file_rollup_v1_sbcp_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSC.ProtoReflect.Descriptor instead.
func (*StartSC) Descriptor() ([]byte, []int) {
	return file_rollup_v1_sbcp_proto_rawDescGZIP(), []int{5}
}

func (x *StartSC) GetSlot() uint64 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *StartSC) GetXtSequenceNumber() uint64 {
	if x != nil {
		return x.XtSequenceNumber
	}
	return 0
}

func (x *StartSC) GetXtRequest() *XTRequest {
	if x != nil {
		return x.XtRequest
	}
	return nil
}

func (x *StartSC) GetXtId() []byte {
	if x != nil {
		return x.XtId
	}
	return nil
}

// Block submission from a sequencer to the SP (deprecated, kept for backward compatibility)
type Block struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainId       []byte                 `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`                     // Which chain's block
	BlockData     []byte                 `protobuf:"bytes,2,opt,name=block_data,json=blockData,proto3" json:"block_data,omitempty"`               // The actual block data
	IncludedXtIds []*XtID                `protobuf:"bytes,3,rep,name=included_xt_ids,json=includedXtIds,proto3" json:"included_xt_ids,omitempty"` // Which xTs are included
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Block) Reset() {
	*x = Block{}
	mi := &file_rollup_v1_sbcp_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_rollup_v1_sbcp_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_rollup_v1_sbcp_proto_rawDescGZIP(), []int{6}
}

func (x *Block) GetChainId() []byte {
	if x != nil {
		return x.ChainId
	}
	return nil
}

func (x *Block) GetBlockData() []byte {
	if x != nil {
		return x.BlockData
	}
	return nil
}

func (x *Block) GetIncludedXtIds() []*XtID {
	if x != nil {
		return x.IncludedXtIds
	}
	return nil
}

var File_rollup_v1_sbcp_proto protoreflect.FileDescriptor

const file_rollup_v1_sbcp_proto_rawDesc = "" +
	"\n" +
	"\x14rollup/v1/sbcp.proto\x12\trollup.v1\x1a\x19rollup/v1/consensus.proto\"o\n" +
	"\x0eL2BlockRequest\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\fR\achainId\x12!\n" +
	"\fblock_number\x18\x02 \x01(\x04R\vblockNumber\x12\x1f\n" +
	"\vparent_hash\x18\x03 \x01(\fR\n" +
	"parentHash\"\xce\x01\n" +
	"\tStartSlot\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\x04R\x04slot\x124\n" +
	"\x16next_superblock_number\x18\x02 \x01(\x04R\x14nextSuperblockNumber\x120\n" +
	"\x14last_superblock_hash\x18\x03 \x01(\fR\x12lastSuperblockHash\x12E\n" +
	"\x11l2_blocks_request\x18\x04 \x03(\v2\x19.rollup.v1.L2BlockRequestR\x0fl2BlocksRequest\"D\n" +
	"\vRequestSeal\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\x04R\x04slot\x12!\n" +
	"\fincluded_xts\x18\x02 \x03(\fR\vincludedXts\"\xe8\x01\n" +
	"\x14RollBackAndStartSlot\x12E\n" +
	"\x11l2_blocks_request\x18\x01 \x03(\v2\x19.rollup.v1.L2BlockRequestR\x0fl2BlocksRequest\x12!\n" +
	"\fcurrent_slot\x18\x02 \x01(\x04R\vcurrentSlot\x124\n" +
	"\x16next_superblock_number\x18\x03 \x01(\x04R\x14nextSuperblockNumber\x120\n" +
	"\x14last_superblock_hash\x18\x04 \x01(\fR\x12lastSuperblockHash\"\xdf\x01\n" +
	"\aL2Block\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\x04R\x04slot\x12\x19\n" +
	"\bchain_id\x18\x02 \x01(\fR\achainId\x12!\n" +
	"\fblock_number\x18\x03 \x01(\x04R\vblockNumber\x12\x1d\n" +
	"\n" +
	"block_hash\x18\x04 \x01(\fR\tblockHash\x12*\n" +
	"\x11parent_block_hash\x18\x05 \x01(\fR\x0fparentBlockHash\x12!\n" +
	"\fincluded_xts\x18\x06 \x03(\fR\vincludedXts\x12\x14\n" +
	"\x05block\x18\a \x01(\fR\x05block\"\x95\x01\n" +
	"\aStartSC\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\x04R\x04slot\x12,\n" +
	"\x12xt_sequence_number\x18\x02 \x01(\x04R\x10xtSequenceNumber\x123\n" +
	"\n" +
	"xt_request\x18\x03 \x01(\v2\x14.rollup.v1.XTRequestR\txtRequest\x12\x13\n" +
	"\x05xt_id\x18\x04 \x01(\fR\x04xtId\"z\n" +
	"\x05Block\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\fR\achainId\x12\x1d\n" +
	"\n" +
	"block_data\x18\x02 \x01(\fR\tblockData\x127\n" +
	"\x0fincluded_xt_ids\x18\x03 \x03(\v2\x0f.rollup.v1.XtIDR\rincludedXtIdsB\x9e\x01\n" +
	"\rcom.rollup.v1B\tSbcpProtoP\x01Z=github.com/compose-network/publisher/proto/rollup/v1;rollupv1\xa2\x02\x03RXX\xaa\x02\tRollup.V1\xca\x02\tRollup\\V1\xe2\x02\x15Rollup\\V1\\GPBMetadata\xea\x02\n" +
	"Rollup::V1b\x06proto3"

var (
	file_rollup_v1_sbcp_proto_rawDescOnce sync.Once
	file_rollup_v1_sbcp_proto_rawDescData []byte
)

func file_rollup_v1_sbcp_proto_rawDescGZIP() []byte {
	file_rollup_v1_sbcp_proto_rawDescOnce.Do(func() {
		file_rollup_v1_sbcp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rollup_v1_sbcp_proto_rawDesc), len(file_rollup_v1_sbcp_proto_rawDesc)))
	})
	return file_rollup_v1_sbcp_proto_rawDescData
}

var file_rollup_v1_sbcp_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_rollup_v1_sbcp_proto_goTypes = []any{
	(*L2BlockRequest)(nil),       // 0: rollup.v1.L2BlockRequest
	(*StartSlot)(nil),            // 1: rollup.v1.StartSlot
	(*RequestSeal)(nil),          // 2: rollup.v1.RequestSeal
	(*RollBackAndStartSlot)(nil), // 3: rollup.v1.RollBackAndStartSlot
	(*L2Block)(nil),              // 4: rollup.v1.L2Block
	(*StartSC)(nil),              // 5: rollup.v1.StartSC
	(*Block)(nil),                // 6: rollup.v1.Block
	(*XTRequest)(nil),            // 7: rollup.v1.XTRequest
	(*XtID)(nil),                 // 8: rollup.v1.XtID
}
var file_rollup_v1_sbcp_proto_depIdxs = []int32{
	0, // 0: rollup.v1.StartSlot.l2_blocks_request:type_name -> rollup.v1.L2BlockRequest
	0, // 1: rollup.v1.RollBackAndStartSlot.l2_blocks_request:type_name -> rollup.v1.L2BlockRequest
	7, // 2: rollup.v1.StartSC.xt_request:type_name -> rollup.v1.XTRequest
	8, // 3: rollup.v1.Block.included_xt_ids:type_name -> rollup.v1.XtID
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_rollup_v1_sbcp_proto_init() }
func file_rollup_v1_sbcp_proto_init() {
	if File_rollup_v1_sbcp_proto != nil {
		return
	}
	file_rollup_v1_consensus_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rollup_v1_sbcp_proto_rawDesc), len(file_rollup_v1_sbcp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rollup_v1_sbcp_proto_goTypes,
		DependencyIndexes: file_rollup_v1_sbcp_proto_depIdxs,
		MessageInfos:      file_rollup_v1_sbcp_proto_msgTypes,
	}.Build()
	File_rollup_v1_sbcp_proto = out.File
	file_rollup_v1_sbcp_proto_goTypes = nil
	file_rollup_v1_sbcp_proto_depIdxs = nil
}
