// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: rollup/v1/transport.proto

package rollupv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DisconnectMessage_Reason int32

const (
	DisconnectMessage_REQUESTED      DisconnectMessage_Reason = 0 // Client or server requested disconnect
	DisconnectMessage_PROTOCOL_ERROR DisconnectMessage_Reason = 1 // Protocol violation detected
	DisconnectMessage_TOO_MANY_PEERS DisconnectMessage_Reason = 2 // Connection limit reached
	DisconnectMessage_AUTH_FAILURE   DisconnectMessage_Reason = 3 // Authentication failed
	DisconnectMessage_READ_TIMEOUT   DisconnectMessage_Reason = 4 // Read operation timed out
	DisconnectMessage_WRITE_TIMEOUT  DisconnectMessage_Reason = 5 // Write operation timed out
	DisconnectMessage_NETWORK_ERROR  DisconnectMessage_Reason = 6 // Network-level error
	DisconnectMessage_INTERNAL_ERROR DisconnectMessage_Reason = 7 // Internal server error
	DisconnectMessage_THROTTLED      DisconnectMessage_Reason = 8 // Connection throttled (rate limited)
)

// Enum value maps for DisconnectMessage_Reason.
var (
	DisconnectMessage_Reason_name = map[int32]string{
		0: "REQUESTED",
		1: "PROTOCOL_ERROR",
		2: "TOO_MANY_PEERS",
		3: "AUTH_FAILURE",
		4: "READ_TIMEOUT",
		5: "WRITE_TIMEOUT",
		6: "NETWORK_ERROR",
		7: "INTERNAL_ERROR",
		8: "THROTTLED",
	}
	DisconnectMessage_Reason_value = map[string]int32{
		"REQUESTED":      0,
		"PROTOCOL_ERROR": 1,
		"TOO_MANY_PEERS": 2,
		"AUTH_FAILURE":   3,
		"READ_TIMEOUT":   4,
		"WRITE_TIMEOUT":  5,
		"NETWORK_ERROR":  6,
		"INTERNAL_ERROR": 7,
		"THROTTLED":      8,
	}
)

func (x DisconnectMessage_Reason) Enum() *DisconnectMessage_Reason {
	p := new(DisconnectMessage_Reason)
	*p = x
	return p
}

func (x DisconnectMessage_Reason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DisconnectMessage_Reason) Descriptor() protoreflect.EnumDescriptor {
	return file_rollup_v1_transport_proto_enumTypes[0].Descriptor()
}

func (DisconnectMessage_Reason) Type() protoreflect.EnumType {
	return &file_rollup_v1_transport_proto_enumTypes[0]
}

func (x DisconnectMessage_Reason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DisconnectMessage_Reason.Descriptor instead.
func (DisconnectMessage_Reason) EnumDescriptor() ([]byte, []int) {
	return file_rollup_v1_transport_proto_rawDescGZIP(), []int{4, 0}
}

// HandshakeRequest is sent by the client during authentication
type HandshakeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                 // Client timestamp for replay protection
	PublicKey     []byte                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"` // Client's public key (33 bytes compressed)
	Signature     []byte                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`                  // ECDSA signature over timestamp
	ClientId      string                 `protobuf:"bytes,4,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`    // Optional client identifier
	Nonce         []byte                 `protobuf:"bytes,5,opt,name=nonce,proto3" json:"nonce,omitempty"`                          // Random nonce for replay protection
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeRequest) Reset() {
	*x = HandshakeRequest{}
	mi := &file_rollup_v1_transport_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeRequest) ProtoMessage() {}

func (x *HandshakeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rollup_v1_transport_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeRequest.ProtoReflect.Descriptor instead.
func (*HandshakeRequest) Descriptor() ([]byte, []int) {
	return file_rollup_v1_transport_proto_rawDescGZIP(), []int{0}
}

func (x *HandshakeRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *HandshakeRequest) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *HandshakeRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *HandshakeRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *HandshakeRequest) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

// HandshakeResponse is sent from the server to the client after a handshake request
type HandshakeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`                   // Whether authentication succeeded
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`                          // Error message if rejected
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // Unique session identifier
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeResponse) Reset() {
	*x = HandshakeResponse{}
	mi := &file_rollup_v1_transport_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeResponse) ProtoMessage() {}

func (x *HandshakeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rollup_v1_transport_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeResponse.ProtoReflect.Descriptor instead.
func (*HandshakeResponse) Descriptor() ([]byte, []int) {
	return file_rollup_v1_transport_proto_rawDescGZIP(), []int{1}
}

func (x *HandshakeResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *HandshakeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *HandshakeResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// Ping is sent to check connection liveness
type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Timestamp for latency measurement
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_rollup_v1_transport_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_rollup_v1_transport_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_rollup_v1_transport_proto_rawDescGZIP(), []int{2}
}

func (x *Ping) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// Pong is a response to a Ping message
type Pong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Echo back the timestamp from Ping
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_rollup_v1_transport_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_rollup_v1_transport_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_rollup_v1_transport_proto_rawDescGZIP(), []int{3}
}

func (x *Pong) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// DisconnectMessage is sent when gracefully closing a connection
type DisconnectMessage struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Reason        DisconnectMessage_Reason `protobuf:"varint,1,opt,name=reason,proto3,enum=rollup.v1.DisconnectMessage_Reason" json:"reason,omitempty"` // Disconnect reason code
	Details       string                   `protobuf:"bytes,2,opt,name=details,proto3" json:"details,omitempty"`                                        // Human-readable details (optional)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectMessage) Reset() {
	*x = DisconnectMessage{}
	mi := &file_rollup_v1_transport_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectMessage) ProtoMessage() {}

func (x *DisconnectMessage) ProtoReflect() protoreflect.Message {
	mi := &file_rollup_v1_transport_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectMessage.ProtoReflect.Descriptor instead.
func (*DisconnectMessage) Descriptor() ([]byte, []int) {
	return file_rollup_v1_transport_proto_rawDescGZIP(), []int{4}
}

func (x *DisconnectMessage) GetReason() DisconnectMessage_Reason {
	if x != nil {
		return x.Reason
	}
	return DisconnectMessage_REQUESTED
}

func (x *DisconnectMessage) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

var File_rollup_v1_transport_proto protoreflect.FileDescriptor

const file_rollup_v1_transport_proto_rawDesc = "" +
	"\n" +
	"\x19rollup/v1/transport.proto\x12\trollup.v1\"\xa0\x01\n" +
	"\x10HandshakeRequest\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\fR\tpublicKey\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignature\x12\x1b\n" +
	"\tclient_id\x18\x04 \x01(\tR\bclientId\x12\x14\n" +
	"\x05nonce\x18\x05 \x01(\fR\x05nonce\"d\n" +
	"\x11HandshakeResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\"$\n" +
	"\x04Ping\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\"$\n" +
	"\x04Pong\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\"\x99\x02\n" +
	"\x11DisconnectMessage\x12;\n" +
	"\x06reason\x18\x01 \x01(\x0e2#.rollup.v1.DisconnectMessage.ReasonR\x06reason\x12\x18\n" +
	"\adetails\x18\x02 \x01(\tR\adetails\"\xac\x01\n" +
	"\x06Reason\x12\r\n" +
	"\tREQUESTED\x10\x00\x12\x12\n" +
	"\x0ePROTOCOL_ERROR\x10\x01\x12\x12\n" +
	"\x0eTOO_MANY_PEERS\x10\x02\x12\x10\n" +
	"\fAUTH_FAILURE\x10\x03\x12\x10\n" +
	"\fREAD_TIMEOUT\x10\x04\x12\x11\n" +
	"\rWRITE_TIMEOUT\x10\x05\x12\x11\n" +
	"\rNETWORK_ERROR\x10\x06\x12\x12\n" +
	"\x0eINTERNAL_ERROR\x10\a\x12\r\n" +
	"\tTHROTTLED\x10\bB\xa3\x01\n" +
	"\rcom.rollup.v1B\x0eTransportProtoP\x01Z=github.com/compose-network/publisher/proto/rollup/v1;rollupv1\xa2\x02\x03RXX\xaa\x02\tRollup.V1\xca\x02\tRollup\\V1\xe2\x02\x15Rollup\\V1\\GPBMetadata\xea\x02\n" +
	"Rollup::V1b\x06proto3"

var (
	file_rollup_v1_transport_proto_rawDescOnce sync.Once
	file_rollup_v1_transport_proto_rawDescData []byte
)

func file_rollup_v1_transport_proto_rawDescGZIP() []byte {
	file_rollup_v1_transport_proto_rawDescOnce.Do(func() {
		file_rollup_v1_transport_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rollup_v1_transport_proto_rawDesc), len(file_rollup_v1_transport_proto_rawDesc)))
	})
	return file_rollup_v1_transport_proto_rawDescData
}

var file_rollup_v1_transport_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_rollup_v1_transport_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_rollup_v1_transport_proto_goTypes = []any{
	(DisconnectMessage_Reason)(0), // 0: rollup.v1.DisconnectMessage.Reason
	(*HandshakeRequest)(nil),      // 1: rollup.v1.HandshakeRequest
	(*HandshakeResponse)(nil),     // 2: rollup.v1.HandshakeResponse
	(*Ping)(nil),                  // 3: rollup.v1.Ping
	(*Pong)(nil),                  // 4: rollup.v1.Pong
	(*DisconnectMessage)(nil),     // 5: rollup.v1.DisconnectMessage
}
var file_rollup_v1_transport_proto_depIdxs = []int32{
	0, // 0: rollup.v1.DisconnectMessage.reason:type_name -> rollup.v1.DisconnectMessage.Reason
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rollup_v1_transport_proto_init() }
func file_rollup_v1_transport_proto_init() {
	if File_rollup_v1_transport_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rollup_v1_transport_proto_rawDesc), len(file_rollup_v1_transport_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rollup_v1_transport_proto_goTypes,
		DependencyIndexes: file_rollup_v1_transport_proto_depIdxs,
		EnumInfos:         file_rollup_v1_transport_proto_enumTypes,
		MessageInfos:      file_rollup_v1_transport_proto_msgTypes,
	}.Build()
	File_rollup_v1_transport_proto = out.File
	file_rollup_v1_transport_proto_goTypes = nil
	file_rollup_v1_transport_proto_depIdxs = nil
}
