name: Go workflow

on:
  push:
    branches-ignore:
      - main
      - stage

jobs:
    go:
        runs-on: ubuntu-latest
        env:
            GO_VERSION: 1.24.5
            LINT_VERSION: v2.7.1
        steps:
            - name: Checkout code
              run: |
                git clone --depth=1 --branch="${GITHUB_REF#refs/heads/}" "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" .
                git checkout "$GITHUB_SHA"

            - name: Install Go
              uses: compose-network/github-actions/actions/install-go@v0.8.0
              with:
                go-version: ${{ env.GO_VERSION }}
            
            - name: Build
              run: make build

            - name: Test
              run: make test

            - name: Install Linter
              run: |
                curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin ${{ env.LINT_VERSION }}
                echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

            - name: Lint
              run: make lint